[2025-01-29T12:19:52.935+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T12:19:52.977+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:19:52.999+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:19:53.000+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T12:19:53.027+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): time_Load_redshift> on 2025-01-29 12:17:52.370778+00:00
[2025-01-29T12:19:53.055+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T12:19:53.079+0000] {standard_task_runner.py:72} INFO - Started process 2861 to run task
[2025-01-29T12:19:53.055+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'time_Load_redshift', 'manual__2025-01-29T12:17:52.370778+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpa8vy5nsv']
[2025-01-29T12:19:53.081+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask time_Load_redshift
[2025-01-29T12:19:53.351+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [running]> on host ae52aba2dca2
[2025-01-29T12:19:53.639+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='time_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T12:17:52.370778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T12:17:52.370778+00:00'
[2025-01-29T12:19:53.648+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T12:20:08.433+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T12:20:08.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T12:20:08.451+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T12:20:08.453+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=time_Load_redshift, run_id=manual__2025-01-29T12:17:52.370778+00:00, execution_date=20250129T121752, start_date=20250129T121952, end_date=20250129T122008
[2025-01-29T12:20:08.490+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T12:20:08.508+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T12:20:08.511+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
