[2025-01-29T11:13:01.219+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:13:01.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.download_s3_clean manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.328+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.download_s3_clean manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.336+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:13:01.429+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_s3_clean> on 2025-01-29 11:12:34.645629+00:00
[2025-01-29T11:13:01.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1765) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:13:01.634+0000] {standard_task_runner.py:72} INFO - Started process 1786 to run task
[2025-01-29T11:13:01.692+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'download_s3_clean', 'manual__2025-01-29T11:12:34.645629+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9685cxmz']
[2025-01-29T11:13:01.743+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask download_s3_clean
[2025-01-29T11:13:02.471+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.download_s3_clean manual__2025-01-29T11:12:34.645629+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:13:03.700+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='download_s3_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:12:34.645629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:12:34.645629+00:00'
[2025-01-29T11:13:03.725+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:13:07.373+0000] {logging_mixin.py:190} INFO - Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
[2025-01-29T11:13:07.391+0000] {logging_mixin.py:190} INFO - 0
[2025-01-29T11:13:07.470+0000] {logging_mixin.py:190} INFO - !_S3_download_complete_my_retail_s3.csv!
[2025-01-29T11:13:07.472+0000] {logging_mixin.py:190} INFO - at /opt/***/my_data/my_retail_s3.csv !!!
[2025-01-29T11:13:07.478+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:13:07.501+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:13:07.502+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=download_s3_clean, run_id=manual__2025-01-29T11:12:34.645629+00:00, execution_date=20250129T111234, start_date=20250129T111301, end_date=20250129T111307
[2025-01-29T11:13:07.586+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:13:07.629+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:13:07.632+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
